import { jest } from '@jest/globals';

// Mock for useCookingState hook
export const useCookingState = jest.fn(() => ({
  view: 'input',
  setView: jest.fn(),
  rawText: '',
  setRawText: jest.fn(),
  recipe: null,
  setRecipe: jest.fn(),
  currentStep: 0,
  setCurrentStep: jest.fn(),
  timer: 0,
  setTimer: jest.fn(),
  isTimerRunning: false,
  setIsTimerRunning: jest.fn(),
  currentTime: '12:00',
  isDarkMode: true,
  setIsDarkMode: jest.fn(),
  activeThemeId: 'default',
  setActiveThemeId: jest.fn(),
  theme: {
    id: 'default',
    name: 'Default',
    title: 'Step Cook',
    icon: () => null, // Mock React component
    properties: {
      font: 'font-sans',
      radius: 'rounded-xl',
      buttonStyle: 'base',
    },
    colors: {
      accent: 'text-blue-500',
      accentDarker: 'text-blue-600',
      bgPrimary: 'bg-blue-500',
      bgPrimaryHover: 'hover:bg-blue-600',
      borderAccent: 'border-blue-500',
      shadowAccent: 'shadow-blue-500',

      checkedBgDark: 'bg-gray-800',
      checkedBgLight: 'bg-gray-100',

      rootBgDark: 'bg-gray-950',
      rootBgLight: 'bg-gray-50',

      cardBgDark: 'bg-gray-900',
      cardBgLight: 'bg-white',
    },
  },
  mealieRecipes: [],
  isMealieLoading: false,
  mealieError: null,
  searchTerm: '',
  setSearchTerm: jest.fn(),
  sortOption: 'date',
  setSortOption: jest.fn(),
  modalOpen: false,
  setModalOpen: jest.fn(),
  modalData: { ingredient: '', suggestion: '', loading: false },
  setModalData: jest.fn(),
  cookedModalOpen: false,
  setCookedModalOpen: jest.fn(),
  selectedImage: null,
  setSelectedImage: jest.fn(),
  previewUrl: null,
  setPreviewUrl: jest.fn(),
  isUploading: false,
  setIsUploading: jest.fn(),
  uploadSuccess: false,
  setUploadSuccess: jest.fn(),
  stepParams: { time: '--:--', temp: '---', speed: '---', seconds: 0, reverse: false },
  stepIngredients: [],
  checkedIngredients: new Set(),
  setCheckedIngredients: jest.fn(),
  isGeminiMode: false,
  setIsGeminiMode: jest.fn(),
  timerRef: { current: null },
  fileInputRef: { current: null },
  t: (darkClass: string, lightClass: string) => (true ? darkClass : lightClass), // Mock this based on isDarkMode in mock
  filteredRecipes: [],
  fetchMealieRecipes: jest.fn(),
  loadMealieRecipe: jest.fn(),
  openMealiePage: jest.fn(),
  formatTime: jest.fn((seconds: number) => `00:${seconds.toString().padStart(2, '0')}`),
  handleProcess: jest.fn(),
  openGeminiModal: jest.fn(),
  handleIngredientAction: jest.fn(),
  handleFileChange: jest.fn(),
  handleUpload: jest.fn(),
  generateGeminiRecipe: jest.fn(),
}));

// Re-export original types if needed, but not common for mock files
// import type * as OriginalModule from '../useCookingState';
// export * from '../useCookingState';
