version: '3.8'

services:
  step-cook:
    image: krisanselmo/step-cook:latest
    container_name: step-cook
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_MODEL_NAME=${GEMINI_MODEL_NAME:-gemini-2.5-flash}

      - MEALIE_BASE_URL=${MEALIE_BASE_URL}
      - MEALIE_API_TOKEN=${MEALIE_API_TOKEN}
      - MEALIE_CF_COOKIE=${MEALIE_CF_COOKIE}
    volumes:
      # Holds gemini-preprompt.txt
      - ./private:/app/private
      -
    # Recommended on a Pi 3.
    deploy:
      resources:
        limits:
          memory: 512M
